### ISSUE TITLE
Runing into an issue on a clean vs code build

### ISSUE THREAD

**Issue by Retr0view** [armandsalle/vite-javascript-webflow#5]
im running into this error message when the second i start the local server

 ```
Plugin: vite:eslint
  File: C:/Users/X/Documents/GitHub/Mariam-development/src/main.js
      at formatError (C:\Users\X\Documents\GitHub\Mariam-development\node_modules\vite\dist\node\chunks\dep-f5552faa.js:36769:46)
      at TransformContext.error (C:\Users\X\Documents\GitHub\Mariam-development\node_modules\vite\dist\node\chunks\dep-f5552faa.js:36765:19)
      at TransformContext.transform (C:\Users\X\Documents\GitHub\Mariam-development\node_modules\vite-plugin-eslint\dist\index.js:87:14)
      at async Object.transform (C:\Users\X\Documents\GitHub\Mariam-development\node_modules\vite\dist\node\chunks\dep-f5552faa.js:36985:30)
      at async doTransform (C:\Users\X\Documents\GitHub\Mariam-development\node_modules\vite\dist\node\chunks\dep-f5552faa.js:52060:29) (x6)
22:20:12 [vite] Internal server error: 
C:\Users\X\Documents\GitHub\Mariam-development\src\main.js
  1:51  error  Delete `␍`  prettier/prettier
  2:49  error  Delete `␍`  prettier/prettier
  3:28  error  Delete `␍`  prettier/prettier
  4:1   error  Delete `␍`  prettier/prettier
  5:47  error  Delete `␍`  prettier/prettier
  6:1   error  Delete `␍`  prettier/prettier
  7:14  error  Delete `␍`  prettier/prettier
  8:15  error  Delete `␍`  prettier/prettier
```

**Comment by Retr0view** [comment]
fixed it by adding a simple line to .prettierrc  ->  "endOfLine": "auto",

`{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": false,
  "endOfLine": "auto",
  "singleQuote": true
}`

**Comment by armandsalle** [comment]
Hello 👋 Yes it's a known issue, I never take the take time to fix it.
Thank you for posting your fix, I will add it ASAP to the Prettier config file 🙌
